version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: projeto#Integrador123
      MYSQL_DATABASE: pi_reinados_web
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pproject#Integrador123"]
      timeout: 20s
      retries: 10
      interval: 5s
    networks:
      - backend-network

volumes:
  mysql_data:

networks:
  backend-network:
    driver: bridge
